# .github/workflows/build-wasm.yml
name: Build WASM
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v12
      - run: make apriltag_wasm.js
        working-directory: ./
      - uses: actions/upload-artifact@v3
        with:
          name: wasm-files
          path: |
            html/apriltag_wasm.js
            html/apriltag_wasm.wasm
